server:
  port: 9090

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: hmsSecretKey2024VeryLongSecretKeyForJWTTokenGeneration

management:
  endpoints:
    web:
      exposure:
        include: "*"
